# Stage 1: Build
FROM maven:3.8.4-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml file and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/target/ScholarNoYomeBackend-0.0.1-SNAPSHOT.jar .

# Expose the application port
EXPOSE 1996

# Specify the command to run the application
ENTRYPOINT ["java", "-jar", "app/ScholarNoYomeBackend-0.0.1-SNAPSHOT.jar"]
